server:
  port: 8888

database:
  host: localhost
  port: 3306
  user: root
  password: 123456
  dbname: feedsystem

redis:
  host: localhost
  port: 6379
  password: 
  db: 0

rabbitmq:
  host: localhost
  port: 5672
  username: root
  password: 123456

canal:
  enabled: false
  token: ""

feed:
  following_fanout_threshold: 2000
  active_follower_window_hours: 72
  following_pull_cache_ttl_seconds: 30
  
observability:
  pprof:
    enabled: true
    api_addr: localhost:6060
    worker_addr: localhost:6061
